name: aeroBERTv2
channels:
  - conda-forge
dependencies:
  - python[version='<3.12']
  - transformers
  - ca-certificates
  - openssl
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - certifi
  - lxml
  - tokenizers
  - evaluate
  - scikit-learn
  - sentencepiece
  - pip:
    - seqeval